"""Markdown review rendering — renders final review from state evidence."""

from __future__ import annotations

from paper_agent.state import AgentState


def render_review_markdown(state: AgentState) -> str:
    """Render the final review as a Markdown string."""
    query = state.get("query", "Unknown Topic")
    claims = state.get("claims", [])
    ranked = state.get("ranked_papers", [])
    comparison = state.get("comparison")
    errors = state.get("errors", [])

    lines: list[str] = []
    lines.append(f"# Survey: {query}")
    lines.append("")
    lines.append(f"*Generated by Paper Agent* | Run: `{state.get('run_id', 'N/A')}`")
    lines.append("")

    lines.append("## Key Findings")
    lines.append("")
    if claims:
        for c in claims[:5]:
            lines.append(f"- **{c.claim_type}**: {c.claim_text} [{c.paper_id}, p.{c.page or 'N/A'}]")
    else:
        lines.append("*(No claims extracted yet. Run the full pipeline to populate.)*")
    lines.append("")

    lines.append("## Representative Papers")
    lines.append("")
    lines.append("| Paper | Year | Core Idea | Evidence |")
    lines.append("|:---|:---:|:---|:---|")
    if ranked:
        for p in ranked:
            lines.append(f"| {p.title} | {p.year or 'N/A'} | {p.abstract[:80]}... | [link]({p.url}) |")
    else:
        lines.append("| *(No papers retrieved yet)* ||||")
    lines.append("")

    lines.append("## Method Landscape")
    lines.append("")
    method_claims = [c for c in claims if c.claim_type == "method"]
    if method_claims:
        for c in method_claims:
            lines.append(f"- {c.claim_text}")
    else:
        lines.append("*(Run extraction to populate.)*")
    lines.append("")

    lines.append("## Experimental Comparison")
    lines.append("")
    if comparison and comparison.rows:
        lines.append(f"| Dimension | {' | '.join(comparison.paper_ids)} |")
        lines.append(f"|:---|{':---:|' * len(comparison.paper_ids)}")
        lines.append(f"| *(See comparison.csv)* ||")
    else:
        lines.append("*(Comparison requires ≥2 papers with extracted claims.)*")
    lines.append("")

    lines.append("## Limitations & Open Questions")
    lines.append("")
    limitation_claims = [c for c in claims if c.claim_type == "limitation"]
    if limitation_claims:
        for c in limitation_claims:
            lines.append(f"- {c.claim_text}")
    else:
        lines.append("*(No limitations extracted.)*")
    lines.append("")

    if errors:
        lines.append("## Warnings")
        lines.append("")
        for e in errors:
            lines.append(f"- ⚠️ {e}")
        lines.append("")

    lines.append("## Further Reading")
    lines.append("")
    lines.append("*(Extended reading list will be populated from citation expansion.)*")
    lines.append("")

    return "\n".join(lines)
